# Generated by Django 3.2.2 on 2021-06-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option_1', models.CharField(blank=True, default='Non of the above', max_length=500, null=True)),
                ('option_2', models.CharField(blank=True, default='Non of the above', max_length=500, null=True)),
                ('option_3', models.CharField(blank=True, default='Non of the above', max_length=500, null=True)),
                ('option_4', models.CharField(blank=True, default='Non of the above', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
